apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: DefaultIssuer
  namespace: duckhue01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: duckhuejs@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx