apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  namespace: duckhue01

spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - "100000000"
      resources:
        requests:
          memory: "50Mi"
          cpu: "500m"
        limits:
          memory: "500Mi"
          cpu: "2000m"
